trigger:
- main

jobs:

- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - checkout: self
    submodules: recursive

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda install --yes --file requirements.txt
    displayName: 'Install required software'
