[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "aiedit"
version = "1.0.0"
description = "ML-based alignment-free genome assembly polisher"
authors = [{ name = "Parham Kazemi", email = "pkazemi@bccrc.ca" }]
readme = "README.md"
requires-python = ">=3.10"

[project.scripts]
aiedit = "aiedit.main:main"

[tool.scikit-build]
cmake.args = ["-DCMAKE_PREFIX_PATH={env.CONDA_PREFIX}"]
wheel.expand-macos-universal-tags = true
wheel.packages = ["aiedit"]