from __future__ import annotations
import numpy
import typing
__all__ = ['BFKmerModel', 'Buffer2D', 'CBFKmerModel', 'Edit', 'EditRegionFinder', 'EditType', 'Editor', 'KmerModel', 'ModelInterface', 'SeedGenerator', 'apply_edits']
class BFKmerModel(KmerModel):
    def __init__(self, arg0: str) -> None:
        ...
    def get_kmer_size(self) -> int:
        ...
    def get_num_hashes(self) -> int:
        ...
    def get_seeds(self) -> list[str]:
        ...
    def get_size(self) -> int:
        ...
    def score(self, arg0: numpy.ndarray[numpy.uint64]) -> float:
        ...
class Buffer2D:
    def __getitem__(self, arg0: tuple[int, int]) -> float:
        ...
    def __init__(self, arg0: int, arg1: int) -> None:
        ...
    def __setitem__(self, arg0: tuple[int, int], arg1: float) -> None:
        ...
    @property
    def num_cols(self) -> int:
        ...
    @property
    def num_rows(self) -> int:
        ...
class CBFKmerModel(KmerModel):
    def __init__(self, arg0: str, arg1: str, arg2: list[str]) -> None:
        ...
    def get_kmer_size(self) -> int:
        ...
    def get_num_hashes(self) -> int:
        ...
    def get_seeds(self) -> list[str]:
        ...
    def get_size(self) -> int:
        ...
    def score(self, arg0: numpy.ndarray[numpy.uint64]) -> float:
        ...
class Edit:
    @staticmethod
    def deletion(arg0: int) -> Edit:
        ...
    @staticmethod
    def insertion(arg0: int, arg1: str) -> Edit:
        ...
    @staticmethod
    def substitution(arg0: int, arg1: str) -> Edit:
        ...
    @property
    def new_base(self) -> str:
        ...
    @property
    def position(self) -> int:
        ...
    @property
    def type(self) -> EditType:
        ...
class EditRegionFinder:
    def __init__(self, arg0: str, arg1: KmerModel, arg2: float, arg3: int) -> None:
        ...
    def __iter__(self) -> typing.Iterator[tuple[int, int]]:
        ...
class EditType:
    """
    Members:
    
      SUBSTITUTE
    
      INSERT
    
      DELETE
    """
    DELETE: typing.ClassVar[EditType]  # value = <EditType.DELETE: 2>
    INSERT: typing.ClassVar[EditType]  # value = <EditType.INSERT: 1>
    SUBSTITUTE: typing.ClassVar[EditType]  # value = <EditType.SUBSTITUTE: 0>
    __members__: typing.ClassVar[dict[str, EditType]]  # value = {'SUBSTITUTE': <EditType.SUBSTITUTE: 0>, 'INSERT': <EditType.INSERT: 1>, 'DELETE': <EditType.DELETE: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Editor:
    def __init__(self, arg0: str, arg1: int, arg2: int) -> None:
        ...
    def __iter__(self) -> typing.Iterator[str]:
        ...
    def delete_base(self) -> None:
        ...
    def get_current(self) -> str:
        ...
    def get_num_remaining(self) -> int:
        ...
    def get_size(self) -> int:
        ...
    def insert(self, arg0: str) -> None:
        ...
    def skip(self) -> None:
        ...
    def substitute(self, arg0: str) -> None:
        ...
class KmerModel:
    pass
class ModelInterface:
    def __init__(self, arg0: str, arg1: int, arg2: int, arg3: int, arg4: ...) -> None:
        ...
    def get_signature(self) -> ...:
        ...
    def update(self, arg0: list[int], arg1: list[int]) -> tuple[str, float]:
        ...
class SeedGenerator:
    def __init__(self, arg0: int, arg1: int, arg2: float) -> None:
        ...
    def generate(self, arg0: int, arg1: int, arg2: int, arg3: int) -> list[str]:
        ...
def apply_edits(arg0: str, arg1: list, arg2: float) -> str:
    ...
