from __future__ import annotations

import typing

import numpy

__all__ = [
    "BFKmerModel",
    "Buffer2D",
    "CBFKmerModel",
    "Edit",
    "EditList",
    "EditRegionFinder",
    "EditStatus",
    "EditType",
    "Editor",
    "KmerModel",
    "ModelInterface",
    "Polisher",
    "SeedGenerator",
]

class BFKmerModel(KmerModel):
    def __init__(self, seeds_bf_path: str, kmers_bf_path: str) -> None: ...
    def get_kmer_size(self) -> int: ...
    def get_kmers_fpr(self) -> float: ...
    def get_num_hashes(self) -> int: ...
    def get_seeds(self) -> list[str]: ...
    def get_seeds_fpr(self) -> float: ...
    def get_size(self) -> int: ...
    def mean_score(self, arg0: str) -> float: ...
    def score(self, hashes: numpy.ndarray[numpy.uint64]) -> float: ...

class Buffer2D:
    def __getitem__(self, arg0: tuple[int, int]) -> float: ...
    def __init__(self, arg0: int, arg1: int) -> None: ...
    def __setitem__(self, arg0: tuple[int, int], arg1: float) -> None: ...
    @property
    def num_cols(self) -> int: ...
    @property
    def num_rows(self) -> int: ...

class CBFKmerModel(KmerModel):
    @typing.overload
    def __init__(
        self, seeds_bf_path: str, kmers_bf_path: str, hist_path: str
    ) -> None: ...
    @typing.overload
    def __init__(self, seeds_bf_path: str, kmers_bf_path: str) -> None: ...
    def get_kmer_size(self) -> int: ...
    def get_kmers_fpr(self) -> float: ...
    def get_num_hashes(self) -> int: ...
    def get_seeds(self) -> list[str]: ...
    def get_seeds_fpr(self) -> float: ...
    def get_size(self) -> int: ...
    def mean_score(self, arg0: str) -> float: ...
    def score(self, hashes: numpy.ndarray[numpy.uint64]) -> float: ...

class Edit:
    edited: str
    i_try: int
    kmer_score: float
    model_confidence: float
    num_kmers: int
    position: int
    status: EditStatus
    type: EditType
    def __init__(self) -> None: ...

class EditList:
    def __init__(self) -> None: ...
    def __iter__(self) -> typing.Iterator[Edit]: ...
    def __len__(self) -> int: ...
    def add(self, edit: Edit) -> None: ...
    def apply(self, seq: str) -> str: ...
    def get_num_passed(self) -> int: ...
    def sort(self) -> None: ...

class EditRegionFinder:
    def __init__(self, arg0: str, arg1: KmerModel, arg2: float) -> None: ...
    def __iter__(self) -> typing.Iterator[tuple[int, int]]: ...

class EditStatus:
    """
    Members:

      PASS

      LOW_KMER_SCORE

      MODEL_FAIL
    """

    LOW_KMER_SCORE: typing.ClassVar[
        EditStatus
    ]  # value = <EditStatus.LOW_KMER_SCORE: 1>
    MODEL_FAIL: typing.ClassVar[EditStatus]  # value = <EditStatus.MODEL_FAIL: 2>
    PASS: typing.ClassVar[EditStatus]  # value = <EditStatus.PASS: 0>
    __members__: typing.ClassVar[
        dict[str, EditStatus]
    ]  # value = {'PASS': <EditStatus.PASS: 0>, 'LOW_KMER_SCORE': <EditStatus.LOW_KMER_SCORE: 1>, 'MODEL_FAIL': <EditStatus.MODEL_FAIL: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class EditType:
    """
    Members:

      SUBSTITUTE

      INSERT

      DELETE
    """

    DELETE: typing.ClassVar[EditType]  # value = <EditType.DELETE: 2>
    INSERT: typing.ClassVar[EditType]  # value = <EditType.INSERT: 1>
    SUBSTITUTE: typing.ClassVar[EditType]  # value = <EditType.SUBSTITUTE: 0>
    __members__: typing.ClassVar[
        dict[str, EditType]
    ]  # value = {'SUBSTITUTE': <EditType.SUBSTITUTE: 0>, 'INSERT': <EditType.INSERT: 1>, 'DELETE': <EditType.DELETE: 2>}
    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Editor:
    def __init__(self, seq: str, start_pos: int, end_pos: int) -> None: ...
    def __iter__(self) -> typing.Iterator[str]: ...
    def delete_base(self) -> None: ...
    def get_current(self) -> str: ...
    def get_num_remaining(self) -> int: ...
    def get_size(self) -> int: ...
    def insert(self, base: str) -> None: ...
    def skip(self) -> None: ...
    def substitute(self, new_base: str) -> None: ...

class KmerModel:
    pass

class ModelInterface:
    def __init__(
        self,
        seq: str,
        start_kmer: int,
        end_kmer: int,
        max_mismatches: int,
        max_indels: int,
        kmer_model: KmerModel,
    ) -> None: ...
    def get_signature(self) -> Buffer2D: ...
    def update(self, arg0: int) -> tuple[EditType, str, float]: ...

class Polisher:
    def __init__(
        self,
        model_path: str,
        kmer_model: KmerModel,
        num_threads: int,
        min_score: float,
        num_tries: int,
        max_gap: int,
    ) -> None: ...
    def get_max_indels(self) -> int: ...
    def get_max_mismatches(self) -> int: ...
    def polish(self, seq: str) -> EditList: ...

class SeedGenerator:
    def __init__(
        self,
        population_size: int,
        max_generations: int,
        mutation_probability: float,
        random_seed: int | None = None,
    ) -> None: ...
    def generate(
        self, num_seeds: int, kmer_size: int, max_mismatches: int, max_indels: int
    ) -> list[str]: ...
